[package]
name = "childe"
version = "0.1.0"
edition = "2021"

[dependencies]
human-panic = "1.2.0"
clap = { version = "4.3.0", features = ["derive"] }
swayipc = "3.0.1"
tokio = "1.32.0"
trawlcat = "0.2.5"
